#ifndef IMPLEMENTATIONS_H
#define IMPLEMENTATIONS_H

#define NN_ARENA_IMPLEMENTATION 
#include "arena.h"
#undef NN_ARENA_IMPLEMENTATION 

#define NN_MAT_IMPLEMENTATION
#include "matrix.h"
#undef NN_MAT_IMPLEMENTATION

#define NN_IMPLEMENTATION 
#include "nn.h"
#undef NN_IMPLEMENTATION

#endif // IMPLEMENTATIONS_H
